### ISSUE TITLE
Swap doesn't work

### ISSUE THREAD

**Issue by bd901029** [tinymanorg/tinyman-js-sdk#66]
Hello @edizcelik I'm trying to convert 8 Algo to USDC. I followed the guide, but still getting error.

My codebase is:

const account = algosdk.mnemonicToSecretKey(mnemonic)
		const accountInfo = await getAccountInformation(this.core.client, account.addr)
		const decimals = accountInfo['apps-total-schema']['num-uint']

		const assetIn = {
			id: 0,
			decimals: 1,
			unit_name: 'ALGO',
		}

		const assetOut = {
			id: process.env.ALGO_USDC_ASSET_ID,
			decimals,
			unit_name: 'USDC',
		}

		// 1.
		const poolInfo = await getPoolInfo(this.core.client, {
			validatorAppID: this.appId,
			asset1ID: assetIn.id,
			asset2ID: assetOut.id
		})
		console.log('poolInfo', poolInfo)
		if (!isPoolReady(poolInfo)) return

		const poolReserves = await getPoolReserves(this.core.client, poolInfo)
		console.log('poolReserves', poolReserves)
		if (isPoolEmpty(poolReserves)) return

		// 2.
		const swapQuote = getSwapQuote(
			SwapType.FixedOutput,
			poolInfo,
			poolReserves,
			{
				assetID: assetOut.id,
				amount
			},
			{
				assetIn: assetIn.decimals,
				assetOut: assetOut.decimals
			}
		)
		console.log('swapQuote', swapQuote)

		// 3.
		const slippage = 0.01
		const accountAddress = account.addr
		const swapTxns = await generateSwapTransactions({
			client: this.core.client,
			pool: poolInfo,
			swapType: SwapType.FixedInput, // or, SwapType.FixedOutput
			assetIn: {
				assetID: parseInt(swapQuote.assetInID),
				amount: Number(swapQuote.assetInAmount)
			},
			assetOut: {
				assetID: parseInt(swapQuote.assetOutID),
				amount: Number(swapQuote.assetOutAmount)
			},
			slippage,
			initiatorAddr: accountAddress
		});

		// 4.
		const signedTxns = await signSwapTransactions({
			pool: poolInfo,
			txGroup: swapTxns,
			initiatorSigner: (value) => {
				console.log('value', value)
			}
		})

		// 5.
		const data = await issueSwap({
			client: this.core.client,
			pool: poolInfo,
			txGroup: swapTxns,
			signedTxns,
			swapType: SwapType.FixedInput,
			initiatorAddr: account.addr,
		})
		console.log('data', data)

At 4th steps, initiatorSigner callback gives me an array. but 4th step is crash with following error:

TypeError: Invalid attempt to destructure non-iterable instance.
In order to be iterable, non-array objects must have a [Symbol.iterator]() method.

Can you plz lemme know the reason?

**Comment by edizcelik** [comment]
@bd901029 The error is thrown because this [line](https://github.com/tinymanorg/tinyman-js-sdk/blob/main/src/swap.ts#L97) in the implementation of signSwapTransactions. This is because you currently don't have a working implementation for `signedTxns` and initiatorSigner is returning undefined. To be able to write `value` to the console, you can do this:

```
  signSwapTransactions({
    pool: poolInfo,
    txGroup: swapTxns,
    initiatorSigner(value) {
      console.log(value);

      // dummy return of a Promise that resolves with empty array, just to be able to console.log(value) while trying to implement initiatorSigner.
      return new Promise((res) => res([]));
    }
  });
```

This should resolve the TypeError issue. By the way, I noticed in the code you shared that the decimals for the assets seem to be wrong. Both ALGO and USDC have decimals value of 6.

**Comment by bd901029** [comment]
Hello @edizcelik Thanks for the reply.

I changed the codebase as you mentioned. it gives me signedTxns like this:

signedTxns [
  undefined,
  Uint8Array(1122) [
    130, 164, 108, 115, 105, 103, 129, 161, 108, 197,   3,  92,
      4,  32,   8,   1,   0,   0, 189, 174, 254,   4,   3,   4,
      5,   6,  37,  36,  13,  68,  49,   9,  50,   3,  18,  68,
     49,  21,  50,   3,  18,  68,  49,  32,  50,   3,  18,  68,
     50,   4,  34,  13,  68,  51,   1,   0,  49,   0,  18,  68,
     51,   1,  16,  33,   7,  18,  68,  51,   1,  24, 129, 172,
    215, 222,  29,  18,  68,  51,   1,  25,  34,  18,  51,   1,
     27,  33,   4,  18,  16,  55,   1,  26,   0, 128,   9,  98,
    111, 111, 116, 115,
    ... 1022 more items
  ],
  undefined,
  Uint8Array(1096) [
    130, 164, 108, 115, 105, 103, 129, 161, 108, 197,   3,  92,
      4,  32,   8,   1,   0,   0, 189, 174, 254,   4,   3,   4,
      5,   6,  37,  36,  13,  68,  49,   9,  50,   3,  18,  68,
     49,  21,  50,   3,  18,  68,  49,  32,  50,   3,  18,  68,
     50,   4,  34,  13,  68,  51,   1,   0,  49,   0,  18,  68,
     51,   1,  16,  33,   7,  18,  68,  51,   1,  24, 129, 172,
    215, 222,  29,  18,  68,  51,   1,  25,  34,  18,  51,   1,
     27,  33,   4,  18,  16,  55,   1,  26,   0, 128,   9,  98,
    111, 111, 116, 115,
    ... 996 more items
  ]
]

and then I call issueSwap() like this:

const data = await issueSwap({
			client: this.core.client,
			pool: poolInfo,
			txGroup: swapTxns,
			signedTxns,
			swapType: SwapType.FixedInput,
			initiatorAddr: account.addr,
		})

and then it crashes:

a [Error]: Array elements must be byte arrays
    at /Volumes/WORK/AutoBookie/autobookie-backend/node_modules/@tinymanorg/tinyman-js-sdk/dist/index.js:3:45061
    at p (/Volumes/WORK/AutoBookie/autobookie-backend/node_modules/@tinymanorg/tinyman-js-sdk/dist/index.js:3:1230)
    at Generator._invoke (/Volumes/WORK/AutoBookie/autobookie-backend/node_modules/@tinymanorg/tinyman-js-sdk/dist/index.js:3:983)
    at Generator.throw (/Volumes/WORK/AutoBookie/autobookie-backend/node_modules/@tinymanorg/tinyman-js-sdk/dist/index.js:3:1593)
    at u (/Volumes/WORK/AutoBookie/autobookie-backend/node_modules/@tinymanorg/tinyman-js-sdk/dist/index.js:3:6469)
    at i (/Volumes/WORK/AutoBookie/autobookie-backend/node_modules/@tinymanorg/tinyman-js-sdk/dist/index.js:3:6708)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  data: a [Error]: Array elements must be byte arrays
      at /Volumes/WORK/AutoBookie/autobookie-backend/node_modules/@tinymanorg/tinyman-js-sdk/dist/index.js:3:15288
      at p (/Volumes/WORK/AutoBookie/autobookie-backend/node_modules/@tinymanorg/tinyman-js-sdk/dist/index.js:3:1230)
      at Generator._invoke (/Volumes/WORK/AutoBookie/autobookie-backend/node_modules/@tinymanorg/tinyman-js-sdk/dist/index.js:3:983)
      at Generator.next (/Volumes/WORK/AutoBookie/autobookie-backend/node_modules/@tinymanorg/tinyman-js-sdk/dist/index.js:3:1593)
      at u (/Volumes/WORK/AutoBookie/autobookie-backend/node_modules/@tinymanorg/tinyman-js-sdk/dist/index.js:3:6469)
      at o (/Volumes/WORK/AutoBookie/autobookie-backend/node_modules/@tinymanorg/tinyman-js-sdk/dist/index.js:3:6672)
      at /Volumes/WORK/AutoBookie/autobookie-backend/node_modules/@tinymanorg/tinyman-js-sdk/dist/index.js:3:6731
      at new Promise (<anonymous>)
      at /Volumes/WORK/AutoBookie/autobookie-backend/node_modules/@tinymanorg/tinyman-js-sdk/dist/index.js:3:6612
      at q (/Volumes/WORK/AutoBookie/autobookie-backend/node_modules/@tinymanorg/tinyman-js-sdk/dist/index.js:3:15450) {
    data: TypeError: Array elements must be byte arrays
        at new SendRawTransaction (/Volumes/WORK/AutoBookie/autobookie-backend/node_modules/algosdk/src/client/v2/algod/sendRawTransaction.ts:35:15)
        at AlgodClient.sendRawTransaction (/Volumes/WORK/AutoBookie/autobookie-backend/node_modules/algosdk/src/client/v2/algod/algod.ts:123:12)
        at /Volumes/WORK/AutoBookie/autobookie-backend/node_modules/@tinymanorg/tinyman-js-sdk/dist/index.js:3:14926
        at p (/Volumes/WORK/AutoBookie/autobookie-backend/node_modules/@tinymanorg/tinyman-js-sdk/dist/index.js:3:1230)
        at Generator._invoke (/Volumes/WORK/AutoBookie/autobookie-backend/node_modules/@tinymanorg/tinyman-js-sdk/dist/index.js:3:983)
        at Generator.next (/Volumes/WORK/AutoBookie/autobookie-backend/node_modules/@tinymanorg/tinyman-js-sdk/dist/index.js:3:1593)
        at u (/Volumes/WORK/AutoBookie/autobookie-backend/node_modules/@tinymanorg/tinyman-js-sdk/dist/index.js:3:6469)
        at o (/Volumes/WORK/AutoBookie/autobookie-backend/node_modules/@tinymanorg/tinyman-js-sdk/dist/index.js:3:6672)
        at /Volumes/WORK/AutoBookie/autobookie-backend/node_modules/@tinymanorg/tinyman-js-sdk/dist/index.js:3:6731
        at new Promise (<anonymous>),
    type: 'Unknown'
  },
  type: 'Unknown'
}

Can you plz take a look?

**Comment by edizcelik** [comment]
The implementation for initiatorSigner I offered was a dummy implementation to get around the TypeError you mentioned and to be able to console log the arguments passed to it. However, you need to implement the `initiatorSigner` in a way so that it signs the transactions that needs to be signed by the account. For example, for swap, the returned value from `generateSwapTransactions` includes a `signers` property which is an array of account addresses that needs to sign that txn. So, in your initiatorSigner implementation, you need to check `signers` array and sign the transactions that you need to. You can either use your secret key to sign using Algosdk or integrate your app with an external wallet and sign the transaction through them. An example implementation could be something like this:

```typescript
  signSwapTransactions({
    pool: poolInfo,
    txGroup: swapTxns,
    initiatorSigner: async (txGroups) => {
      const toBeSigned = txGroups.flatMap(
          txGroup => txGroup.filter((item) => item.signers.includes(accountAddress))
      );
      let signed: Uint8Array[] = [];

      for (let item of toBeSigned) {
          const {blob} = await algosdk.signTransaction(item.txn, accountSecretKey);
          signed.push(blob);
      }

       return signed;
    }
  });
```

You need to make sure what you return from `initiatorSigner` is a Promise of `Uint8Array[]`. So, the initiatorSigner's shape is defined like this, https://github.com/tinymanorg/tinyman-js-sdk/blob/main/src/util/commonTypes.ts#L13:

```
type InitiatorSigner = (txGroupList: SignerTransaction[][]) => Promise<Uint8Array[]>
```

**Comment by bd901029** [comment]
Hello @edizcelik 

Thanks for your detailed codebase. I followed it and it appears there is an issue on your teal code:

a [Error]: assert failed pc=909. Details: pc=909, opcodes===
&&
assert
    at /Volumes/WORK/AutoBookie/autobookie-backend/node_modules/@tinymanorg/tinyman-js-sdk/dist/index.js:3:45061
    at p (/Volumes/WORK/AutoBookie/autobookie-backend/node_modules/@tinymanorg/tinyman-js-sdk/dist/index.js:3:1230)
    at Generator._invoke (/Volumes/WORK/AutoBookie/autobookie-backend/node_modules/@tinymanorg/tinyman-js-sdk/dist/index.js:3:983)
    at Generator.throw (/Volumes/WORK/AutoBookie/autobookie-backend/node_modules/@tinymanorg/tinyman-js-sdk/dist/index.js:3:1593)
    at u (/Volumes/WORK/AutoBookie/autobookie-backend/node_modules/@tinymanorg/tinyman-js-sdk/dist/index.js:3:6469)
    at i (/Volumes/WORK/AutoBookie/autobookie-backend/node_modules/@tinymanorg/tinyman-js-sdk/dist/index.js:3:6708)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  data: a [Error]: assert failed pc=909. Details: pc=909, opcodes===
  &&
  assert
      at /Volumes/WORK/AutoBookie/autobookie-backend/node_modules/@tinymanorg/tinyman-js-sdk/dist/index.js:3:15288
      at p (/Volumes/WORK/AutoBookie/autobookie-backend/node_modules/@tinymanorg/tinyman-js-sdk/dist/index.js:3:1230)
      at Generator._invoke (/Volumes/WORK/AutoBookie/autobookie-backend/node_modules/@tinymanorg/tinyman-js-sdk/dist/index.js:3:983)
      at Generator.throw (/Volumes/WORK/AutoBookie/autobookie-backend/node_modules/@tinymanorg/tinyman-js-sdk/dist/index.js:3:1593)
      at u (/Volumes/WORK/AutoBookie/autobookie-backend/node_modules/@tinymanorg/tinyman-js-sdk/dist/index.js:3:6469)
      at i (/Volumes/WORK/AutoBookie/autobookie-backend/node_modules/@tinymanorg/tinyman-js-sdk/dist/index.js:3:6708)
      at processTicksAndRejections (node:internal/process/task_queues:96:5) {
    data: Error: Network request error. Received status 400: TransactionPool.Remember: transaction 67BSBJYXVEAJC66HFBME2UWWUWF6CMAK4F76GKMJLZHJPAALTZJA: logic eval error: assert failed pc=909. Details: pc=909, opcodes===
    &&
    assert
    
        at Request.callback (/Volumes/WORK/AutoBookie/autobookie-backend/node_modules/superagent/src/node/index.js:879:15)
        at fn (/Volumes/WORK/AutoBookie/autobookie-backend/node_modules/superagent/src/node/index.js:1130:18)
        at IncomingMessage.<anonymous> (/Volumes/WORK/AutoBookie/autobookie-backend/node_modules/superagent/src/node/parsers/image.js:8:5)
        at IncomingMessage.emit (node:events:525:35)
        at endReadableNT (node:internal/streams/readable:1358:12)
        at processTicksAndRejections (node:internal/process/task_queues:83:21) {
      status: 400,
      response: [Object]
    },
    type: 'LogicError'
  },
  type: 'Unknown'
}

Can you plz check it?

Thanks.

**Comment by fergalwalsh** [comment]
The error you are getting comes from this line of the contract: https://github.com/tinymanorg/tinyman-contracts-v1/blob/main/contracts/validator_approval.teal#L884

It means the swap transaction group is not correct - the input & output assets do not match the pool's assets.

**Comment by bd901029** [comment]
hello @fergalwalsh I attached the log of swap transaction group:

swapTxns [
  {
    txn: Transaction {
      name: 'Transaction',
      tag: <Buffer 54 58>,
      from: [Object],
      to: [Object],
      amount: 2000,
      note: [Uint8Array],
      type: 'pay',
      flatFee: false,
      genesisHash: <Buffer 48 63 b5 18 a4 b3 c8 4e c8 10 f2 2d 4f 10 81 cb 0f 71 f0 59 a7 ac 20 de c6 2f 7f 70 e5 09 3a 22>,
      fee: 1000,
      firstRound: 25542671,
      lastRound: 25543671,
      genesisID: 'testnet-v1.0',
      appArgs: [],
      lease: Uint8Array(0) [],
      group: <Buffer b2 f3 c5 61 d7 38 e0 f4 0b cf 93 9e de 65 53 f5 02 9e 42 f2 ba e3 dd f7 a3 cf eb 65 0c a4 a3 65>
    },
    signers: [ '44JWBWM3YFHZWSY5D6EU2RUHR6FIXIP3N4ENMV2I6PBIG6PPWRTYQVGAEY' ]
  },
  {
    txn: Transaction {
      name: 'Transaction',
      tag: <Buffer 54 58>,
      type: 'appl',
      from: [Object],
      appIndex: 62368684,
      appOnComplete: 0,
      appArgs: [Array],
      appAccounts: [Array],
      appForeignAssets: [Array],
      note: Uint8Array(0) [],
      lease: Uint8Array(0) [],
      flatFee: false,
      genesisHash: <Buffer 48 63 b5 18 a4 b3 c8 4e c8 10 f2 2d 4f 10 81 cb 0f 71 f0 59 a7 ac 20 de c6 2f 7f 70 e5 09 3a 22>,
      fee: 1000,
      firstRound: 25542671,
      lastRound: 25543671,
      genesisID: 'testnet-v1.0',
      group: <Buffer b2 f3 c5 61 d7 38 e0 f4 0b cf 93 9e de 65 53 f5 02 9e 42 f2 ba e3 dd f7 a3 cf eb 65 0c a4 a3 65>
    },
    signers: [ 'JOEPFUDG7NS4EEUM7WZW7GA6VLD3STS5DDCJWKSGB2QLHIWDF2CJMXEFTM' ]
  },
  {
    txn: Transaction {
      name: 'Transaction',
      tag: <Buffer 54 58>,
      type: 'axfer',
      from: [Object],
      to: [Object],
      amount: 5,
      assetIndex: 10458941,
      note: Uint8Array(0) [],
      flatFee: false,
      genesisHash: <Buffer 48 63 b5 18 a4 b3 c8 4e c8 10 f2 2d 4f 10 81 cb 0f 71 f0 59 a7 ac 20 de c6 2f 7f 70 e5 09 3a 22>,
      fee: 1000,
      firstRound: 25542671,
      lastRound: 25543671,
      genesisID: 'testnet-v1.0',
      appArgs: [],
      lease: Uint8Array(0) [],
      group: <Buffer b2 f3 c5 61 d7 38 e0 f4 0b cf 93 9e de 65 53 f5 02 9e 42 f2 ba e3 dd f7 a3 cf eb 65 0c a4 a3 65>
    },
    signers: [ '44JWBWM3YFHZWSY5D6EU2RUHR6FIXIP3N4ENMV2I6PBIG6PPWRTYQVGAEY' ]
  },
  {
    txn: Transaction {
      name: 'Transaction',
      tag: <Buffer 54 58>,
      type: 'axfer',
      from: [Object],
      to: [Object],
      amount: 7n,
      assetIndex: 10458941,
      note: Uint8Array(0) [],
      flatFee: false,
      genesisHash: <Buffer 48 63 b5 18 a4 b3 c8 4e c8 10 f2 2d 4f 10 81 cb 0f 71 f0 59 a7 ac 20 de c6 2f 7f 70 e5 09 3a 22>,
      fee: 1000,
      firstRound: 25542671,
      lastRound: 25543671,
      genesisID: 'testnet-v1.0',
      appArgs: [],
      lease: Uint8Array(0) [],
      group: <Buffer b2 f3 c5 61 d7 38 e0 f4 0b cf 93 9e de 65 53 f5 02 9e 42 f2 ba e3 dd f7 a3 cf eb 65 0c a4 a3 65>
    },
    signers: [ 'JOEPFUDG7NS4EEUM7WZW7GA6VLD3STS5DDCJWKSGB2QLHIWDF2CJMXEFTM' ]
  }
]

I'm not sure what's wrong here, because this transaction group is the result of generateSwapTransactions()...

**Comment by edizcelik** [comment]
From the transactions generated, it seems you are trying to use ALGO/USDC pool but provided USDC as both assetIn and assetOut to generateSwapTransactions.
